### ISSUE TITLE
Cannot specify version range for prerequisite

### ISSUE THREAD

**Issue by gflohr** [avar/dist-zilla-plugin-makemaker-awesome#12]
I have this in my `dist.in`:

```ini
[Prereqs]
perl = 5.018
ExtUtils::MakeMaker = 7.1101
URI::git = 0.02
JavaScript::Duktape::XS = 0.000074, <= 0.000074
```

When I try `dzil build`, it terminates with code 2 and this output.

```shell
$ dzil build
[DZ] beginning to build Qgoda
[@Filter/ExtraTests] rewriting author test xt/author/critic.t
[@Filter/ExtraTests] rewriting release test xt/release/cpan-changes.t
[@Filter/ExtraTests] rewriting author test xt/author/pod-syntax.t
[PkgVersion] skipping lib/Qgoda.pm: assigns to $VERSION
[DZ] guessing dist's main_module is lib/Qgoda.pm
[MakeMaker::Awesome] found version range in runtime prerequisites, which ExtUtils::MakeMaker cannot parse (must specify eumm_version of at least 7.1101): JavaScript::Duktape::XS == 0.000074
[MakeMaker::Awesome] found version range in runtime prerequisites, which ExtUtils::MakeMaker cannot parse (must specify eumm_version of at least 7.1101): JavaScript::Duktape::XS == 0.000074 at inline delegation in Dist::Zilla::Plugin::MakeMaker::Awesome for logger->log_fatal (attribute declared in /path/to/home/perl5/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0/Dist/Zilla/Role/Plugin.pm at line 59) line 18.
```

I have EUMM version 7.44 installed. But the plugin method `eumm_version()` reports a EUMM version of 0.

You can reproduce this problem with commit `eabffd70e5be759183d1445996e62e98acbfdd95` of https://github.com/gflohr/qgoda.

**Comment by karenetheridge** [comment]
`eumm_version` is a configuration value you provide to the plugin. It sets the minimum necessary version of ExtUtils::MakeMaker the user must have to install the module. That must be 7.1101 or higher, not the default of 0.

This is demonstrated in t/plugins/makemaker.t in the Dist-Zilla distribution.

**Comment by gflohr** [comment]
Thanks for the quick help!

I had checked https://metacpan.org/source/ETHER/Dist-Zilla-Plugin-PromptIfStale-0.041/dist.ini. Shouldn't that then also use `eumm_version`?

**Comment by karenetheridge** [comment]
That release is five years old and there have been 14 releases since then.

https://github.com/karenetheridge/Dist-Zilla-Plugin-PromptIfStale/commit/de899b8

https://github.com/karenetheridge/Dist-Zilla-Plugin-PromptIfStale/blob/master/dist.ini#L49-L58

**Comment by gflohr** [comment]
Yes, sorry.

I followed a link to an EUMM issue from the source code, from there to metacpan, and didn't notice that I was looking at an outdated version, my bad.
