### ISSUE TITLE
Option to setup PL_FILES

### ISSUE THREAD

**Issue by atoomic** [avar/dist-zilla-plugin-makemaker-awesome#13]
We can use `exe_file` to setup one or more exe files which will be added to `EXE_FILE` section.
I wonder if we could not consider something similar for the `PL_FILES` by using `pl_file` in `[MakeMaker::Awesome]` section?

**Comment by karenetheridge** [comment]
exe_file has its own hook because executables are provided from Dist::Zilla using the core :ExecFiles filefinder.  There is no such corresponding core provider for pl files, so there is no specific need to wire up an attribute dedicated to it.  If you want to populate `PL_FILES` in the makemaker args, you can do so via `WriteMakefile_arg = PL_FILES = { ... }`.

**Comment by atoomic** [comment]
@karenetheridge I was thinking something like this https://github.com/avar/dist-zilla-plugin-makemaker-awesome/pull/14

**Comment by karenetheridge** [comment]
Could you explain your problem a little better, and why the above example I provided wouldn't work?

**Comment by atoomic** [comment]
I think your example above using `WriteMakefile_arg` would work fine in my case where I have a `bin/Dynamic.PL` file generating a `bin/Dynamic` file which need to be added to the `EXE_FILES` section.

I was experimenting with that solution before reading your answer (and unfortunately irccloud platform is currently not available... )

I thought this was a good idea to be able to provide `pl_file` in the same way as `exe_file`, so for the common and simple case this avoid working around and providing some custom args via `WriteMakefile_arg`.

`WriteMakefile_arg` can still be used for more complex scenarii.

But if you think this is not necessary, we can close it.

**Comment by atoomic** [comment]
I can confirm that using something like this
```
[@Starter::Git]
...
MakeMaker::Awesome.exe_file = scripts/dynamic
MakeMaker::Awesome.WriteMakefile_arg[] = PL_FILES => { 'scripts/dynamic.PL' => 'scripts/dynamic' }
```
worked fine for me

I was expecting to use something like this and the patch from #14 provides a way to use that syntax
```
[@Starter::Git]
...
MakeMaker::Awesome.exe_file = scripts/dynamic
MakeMaker::Awesome.pl_file = scripts/dynamic.PL
```
