### ISSUE TITLE
@avar: please enable travis for this repository

### ISSUE THREAD

**Issue by karenetheridge** [avar/dist-zilla-plugin-makemaker-awesome#7]
I have created a .travis.yml which "should" work... but I lack the permissions to enable use of it at travis-ci.org.  thanks!

**Comment by avar** [comment]
I haven't enabled Travis before, but I just enabled it in settings, then
signed into Travis and did the whole auth step, and then toggled this repo
in my profile. This should work now unless I missed something.

**Comment by karenetheridge** [comment]
Thanks! I kicked off a build here and will address any issues that pop up.

https://travis-ci.org/avar/dist-zilla-plugin-makemaker-awesome/builds/332025510
